services:
  web:
    # for openresty
    # image: openresty/openresty:buster
    # flask
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    links:
      - redis
    # for openresty
    # volumes:
    #   - ./openresty/conf.d:/etc/nginx/conf.d
    #   - ./openresty/lua:/var/app
  redis:
    image: redis:6.0-alpine